repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: >
          (?x)^(
              ^{{.*}}.*\.yaml$|
              ^.*/templates/.*$
          )
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint
  - repo: https://github.com/bitnami/readme-generator-for-helm
    rev: "2.7.2"
    hooks:
      - id: helm-readme-generator
        # in order to run helm-readme-generator only once
        pass_filenames: false
        always_run: true
        # default args are [--readme=chart/README.md, --values=chart/values.yaml]
        args: [--readme=charts/mailu/README.md, --values=charts/mailu/values.yaml]
