config: .trivy.yaml
debug: false
quiet: true
report: all
exit-code: 0
# ignorefile: .trivyignore
format: sarif
output: trivy-results.sarif
misconfiguration:
  helm:
    values:
      - ./charts/mailu/ci/helm-lint-values.yaml
severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
