hostnames:
  - example.com

domain: example.com

initialAccount:
  enabled: true
  username: mailadmin
  domain: example.com
  password: chang3m3!

secretKey: chang3m3!

subnet: 192.168.0.0/16

networkPolicy:
  enabled: true

persistence:
  single_pvc: false

postgresql:
  enabled: true
  postgresqlUsername: mailu
  postgresqlPassword: chang3m3!
  postgresqlDatabase: mailu
  primary:
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
      limits:
        memory: 500Mi
        cpu: 1

ingress:
  enabled: true
  selfSigned: true
  annotations:
    auth.cluster.arpa/enabled: "false"

front:
  logLevel: INFO
  # image:
  #   tag: master
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m

admin:
  logLevel: DEBUG
  # image:
  #   tag: master
  resources:
    requests:
      memory: 500Mi
      cpu: 100m
    limits:
      memory: 500Mi
      cpu: 1

postfix:
  logLevel: INFO
  # image:
  #   tag: master
  resources:
    requests:
      memory: 2Gi
      cpu: 100m
    limits:
      memory: 2Gi
      cpu: 1

dovecot:
  logLevel: INFO
  # image:
  #   tag: master
  resources:
    requests:
      memory: 500Mi
      cpu: 100m
    limits:
      memory: 500Mi
      cpu: 1

rspamd:
  logLevel: INFO
  # image:
  #   tag: master
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 1

clamav:
  logLevel: INFO
  # image:
  #   tag: master
  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 2Gi
      cpu: 1

webmail:
  logLevel: INFO
  # image:
  #   tag: master
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 1

webdav:
  logLevel: INFO
  image:
    tag: master

fetchmail:
  logLevel: INFO
  # image:
  #   tag: master

redis:
  master:
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
      limits:
        memory: 500Mi
        cpu: 1

tika:
  enabled: true
  languages:
    - en
    - fr

oletools:
  enabled: true

api:
  enabled: true
  token: chang3m3!
