blank_issues_enabled: false
contact_links:
  - name: Ask for help
    url: https://riot.im/app/#/room/!RJFCFtixHgPhzacdhW:tedomum.net
    about: Please don't use the issue tracker for support requests. Use the Matrix channel \#Mailu for support requests. Thank you!
