# This is the definition of the required ssl certificate for the mail system
# It will be issued by cert-manager

#
# Certificate request deployment is only needed if Letsencrypt is
# supposed to be the TLS Flavor
#
{{- $letsEncryptTlsFlavors := list "letsencrypt" "mail-letsencrypt" -}}

{{ if has .Values.ingress.tlsFlavor $letsEncryptTlsFlavors }}

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "mailu.fullname" . }}-certificates
spec:
  secretName: {{ include "mailu.fullname" . }}-certificates
  renewBefore: 1440h # 60d
  commonName: "{{ first (required "hostname" .Values.hostnames) }}"
  dnsNames:
{{- range .Values.hostnames }}
  - "{{ . }}"
{{- end }}
  issuerRef:
    kind: {{ .Values.certmanager.issuerType }}
    name: {{ .Values.certmanager.issuerName }}

{{ else if (eq .Values.ingress.tlsFlavor "notls") }}

# TLS is not needed
# Defining a dummy certificate secret to allow the "front" container
# to start (needs mounting the secrets)

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "mailu.fullname" . }}-certificates
data: {
  tls.crt: 'ZHVtbXk=',
  tls.key: 'ZHVtbXk='
}

{{ end }}
