# This is the definition of the required ssl certificate for the mail system
# It will be issued by cert-manager

apiVersion: {{ default "cert-manager.io/v1alpha2" .Values.certmanager.apiVersion }}
kind: Certificate
metadata:
  name: {{ include "mailu.fullname" . }}-certificates
spec:
  secretName: {{ include "mailu.fullname" . }}-certificates
  renewBefore: 1440h # 60d
  commonName: "{{ first (required "hostname" .Values.hostnames) }}"
  dnsNames:
{{- range .Values.hostnames }}
  - "{{ . }}"
{{- end }}
  issuerRef:
    kind: {{ .Values.certmanager.issuerType }}
    name: {{ .Values.certmanager.issuerName }}
