# This file is derived from https://github.com/Mailu/Mailu/blob/master/docs/kubernetes/mailu/security.yaml
# (file is split into rspamd.yaml and clamav.yaml)

{{- if .Values.clamav.enabled }}

{{ if .Capabilities.APIVersions.Has "apps/v1/Deployment" }}
apiVersion: apps/v1
{{ else }}
apiVersion: apps/v1
{{ end }}
kind: Deployment
metadata:
  name: {{ include "mailu.fullname" . }}-clamav
spec:
  selector:
    matchLabels:
      app: {{ include "mailu.fullname" . }}
      component: clamav
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "mailu.fullname" . }}
        component: clamav
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: clamav
        image: {{ .Values.clamav.image.repository }}:{{ default .Values.mailuVersion .Values.clamav.image.tag }}
        imagePullPolicy: Always
        volumeMounts:
          - name: data
            subPath: clamav
            mountPath: /data
        env:
          - name: LOG_LEVEL
            value: {{ default .Values.logLevel .Values.clamav.logLevel }}
        ports:
          - name: clamav
            containerPort: 3310
            protocol: TCP
        {{- with .Values.clamav.resources }}
        resources:
        {{- .|toYaml|nindent 10}}
        {{- end }}
        livenessProbe:
          # give it 10 minutes for initial freshclam update
          exec:
            command:
              - /health.sh
          periodSeconds: 10
          failureThreshold: 60
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - /health.sh
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
{{- if .Values.clamav.persistence.claimEnabled }}  
{{- if .Values.clamav.persistence.existingClaim }}
            claimName: {{ .Values.clamav.persistence.existingClaim }}
{{- else }}
            {{- $_ := set . "deploy" "clamav" }}
            claimName: {{ include "mailu.deployClaimName" . }}
{{- end }}   
{{- else }}
            claimName: {{ include "mailu.claimName" . }}
{{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.fullname" . }}-clamav
  labels:
    app: {{ include "mailu.fullname" . }}
    component: clamav
spec:
  selector:
    app: {{ include "mailu.fullname" . }}
    component: clamav
  ports:
  - name: clamav
    port: 3310
    protocol: TCP

{{- end }}