# This file is derived from https://github.com/Mailu/Mailu/blob/master/docs/kubernetes/mailu/redis.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailu.fullname" . }}-redis
spec:
  selector:
    matchLabels:
      app: {{ include "mailu.fullname" . }}
      component: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "mailu.fullname" . }}
        component: redis
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: redis
        image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
        imagePullPolicy:  {{ default "Always" .Values.imagePullPolicy }}
        volumeMounts:
          - name: data
            subPath: redis
            mountPath: /data
        ports:
          - containerPort: 6379
            name: redis
            protocol: TCP
        {{- with .Values.redis.resources }}
        resources:
        {{- .|toYaml|nindent 10}}
        {{- end }}
        livenessProbe:
          exec:
            command:
              - /usr/local/bin/redis-cli
              - info
              - status
          periodSeconds: 10
          failureThreshold: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - /usr/local/bin/redis-cli
              - info
              - status
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mailu.claimName" . }}{{ if .Values.combineRspamdAdmin  }}-redis{{ end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.fullname" . }}-redis
  labels:
    app: {{ include "mailu.fullname" . }}
    component: redis
spec:
  selector:
    app: {{ include "mailu.fullname" . }}
    component: redis
  ports:
  - name: redis
    port: 6379
    protocol: TCP


{{ if .Values.combineRspamdAdmin  }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mailu.claimName" . }}-redis
  {{- if .Values.persistence.annotations }}
  annotations:
    helm.sh/resource-policy: "keep"
  {{ toYaml .Values.persistence.annotations | indent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.redis.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{ end }}
