# This file is derived from https://github.com/Mailu/Mailu/blob/master/docs/kubernetes/mailu/security.yaml
# (file is split into rspamd.yaml and clamav.yaml)

{{- $dot := . }}
{{- $files := .Files }}
{{- $deploy := "rspamd" }}
{{- $prefix := printf "%s/%s/"  "files" $deploy }}
{{- $pattern := printf "%s%s" $prefix "**" }}

{{ if .Capabilities.APIVersions.Has "apps/v1/Deployment" }}
apiVersion: apps/v1
{{ else }}
apiVersion: apps/v1
{{ end }}
kind: Deployment
metadata:
  name: {{ include "mailu.fullname" . }}-rspamd
spec:
  selector:
    matchLabels:
      app: {{ include "mailu.fullname" . }}
      component: rspamd
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "mailu.fullname" . }}
        component: rspamd
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: rspamd
        image: {{ .Values.rspamd.image.repository }}:{{ default .Values.mailuVersion .Values.rspamd.image.tag }}
        imagePullPolicy: Always
        volumeMounts:
          - name: data
            subPath: rspamd
            mountPath: /var/lib/rspamd
          - name: data
            subPath: dkim
            mountPath: /dkim  
{{- range $path, $bytes := $files.Glob $pattern }}
{{ $scope := (dict "root" $dot.Values "path" $path "prefix" $prefix) }}
          - name: {{ include "mailu.fullname" $dot }}-rspamd
            mountPath: "{{ $path | replace $prefix "/" }}"
            subPath: {{ include "configmap.key" $scope }}
{{- end }}            
        env:
          - name: LOG_LEVEL
            value: {{ default .Values.logLevel .Values.rspamd.logLevel }}
          - name: FRONT_ADDRESS
            value: {{ include "mailu.fullname" . }}-front
          - name: REDIS_ADDRESS
            value: {{ include "mailu.fullname" . }}-redis
          {{- if .Values.clamav.enabled }}
          - name: ANTIVIRUS
            value: clamav
          - name: ANTIVIRUS_ADDRESS
            value: {{ include "mailu.fullname" . }}-clamav:3310
          {{- else }}
          - name: ANTIVIRUS
            value: none
          - name: ANTIVIRUS_ADDRESS
            value: localhost
          {{- end }}
          - name: SUBNET
            value: "{{ .Values.subnet }}"
        ports:
          - name: rspamd
            containerPort: 11332
            protocol: TCP
          - name: rspamd-http
            containerPort: 11334
            protocol: TCP
        {{- with .Values.rspamd.resources }}
        resources:
        {{- .|toYaml|nindent 10}}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: rspamd-http
          periodSeconds: 5
          failureThreshold: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: rspamd-http
          periodSeconds: 10
          failureThreshold: 1
          timeoutSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
{{- if .Values.rspamd.persistence.claimEnabled }}  
{{- if .Values.rspamd.persistence.existingClaim }}
            claimName: {{ .Values.rspamd.persistence.existingClaim }}
{{- else }}
            {{- $_ := set . "deploy" "rspamd" }}
            claimName: {{ include "mailu.deployClaimName" . }}
{{- end }}   
{{- else }}
            claimName: {{ include "mailu.claimName" . }}
{{- end }} 

        - name: {{ include "mailu.fullname" . }}-rspamd
          configMap:
            name: {{ include "mailu.fullname" . }}-rspamd-map
            items:
{{- range $path, $bytes := $files.Glob $pattern }}
{{ $scope := (dict "root" $dot.Values "path" $path "prefix" $prefix) }}              
              - key: {{ include "configmap.key" $scope }}
                path: {{ include "configmap.key" $scope }}
{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.fullname" . }}-rspamd
  labels:
    app: {{ include "mailu.fullname" . }}
    component: rspamd
spec:
  selector:
    app: {{ include "mailu.fullname" . }}
    component: rspamd
  ports:
  - name: rspamd
    port: 11332
    protocol: TCP
  - name: rspamd-http
    protocol: TCP
    port: 11334
