{{- if and (not .Values.persistence.single_pvc) (.Values.rspamd_clamav_persistence.single_pvc) }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mailu.rspamdClamavClaimName" . }}
{{- if .Values.rspamd_clamav_persistence.annotations }}
  annotations:
{{ toYaml .Values.rspamd_clamav_persistence.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.rspamd_clamav_persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.rspamd_clamav_persistence.size }}
  {{- if .Values.rspamd_clamav_persistence.storageClass }}
  storageClassName: {{ .Values.rspamd_clamav_persistence.storageClass }}
  {{- end }}
{{- end }}
