---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
      releases_info: ${{ toJSON(steps.release.outputs) }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # path: mailu
          # release-type: helm
          # package-name: mailu
          # monorepo-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}
          # changelog-notes-type: github
          # prerelease: true
          include-v-in-tag: false
          tag-separator: '-'
          command: manifest
          # Only check the last 50 commits to avoid rate limiting
          commit-search-depth: 50

      - run: echo $JSON
        name: Release Please Output Info
        env:
          JSON: ${{ toJSON(steps.release.outputs) }}

  packages-calculate:
    if: needs.release-please.outputs.paths_released != '[]'
    name: Packages Calculate
    needs:
      - release-please
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.interrogate.outputs.result }}
    steps:

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - id: interrogate
        uses: actions/github-script@v4
        env:
          PATHS_RELEASED: ${{ needs.release-please.outputs.paths_released }}
          RELEASES_INFO: ${{ needs.release-please.outputs.releases_info }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { PATHS_RELEASED, RELEASES_INFO } = process.env
            const releases = JSON.parse(PATHS_RELEASED)
            const releasesInfo = JSON.parse(RELEASES_INFO)
            const result = []
            for(const release of releases){
              result.push(
                {
                  name: release,
                  version: releasesInfo[`${release}--version`]
                }
              )
            }
            return result

  packages-publish:
    needs:
      - packages-calculate
    name: Charts Packages Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.packages-calculate.outputs.result) }}
    steps:
    - name: Workflow publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GITHUB_TOKEN" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/publish-chart.yaml/dispatches \
        -d '{"ref":"master","inputs":{"package":"${{ matrix.package.name }}","version":"${{ matrix.package.version }}"}}'
