---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[secops] Trivy"

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - master
    paths:
      - .github/**
      - charts/mailu/**
  push:
    branches:
      - master
    paths:
      - charts/mailu/**
      - .github/workflows/trivy.yaml
      - .trivy.yaml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

permissions:
  security-events: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5
        with:
          version: v3.10.0

      - name: Install dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm dependency build charts/mailu

      - name: Set up python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: '3.14'

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # master
        with:
          scan-type: 'config'
          scan-ref: '.'
          trivy-config: '.trivy.yaml'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4
        with:
          sarif_file: 'trivy-results.sarif'
