---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "[secops] Trivy"

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - master
    paths:
      - .github/**
      - charts/mailu/**
  push:
    branches:
      - master
    paths:
      - charts/mailu/**
      - .github/workflows/trivy.yaml
      - .trivy.yaml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

permissions:
  security-events: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5
        with:
          version: v3.21.3

      - name: Install dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm dependency build charts/mailu

      - name: Set up python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: '3.14'

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@c07df6fec6fa692e6fd1200d50aaa1fdd66f03c8 # master
        with:
          scan-type: 'config'
          scan-ref: '.'
          trivy-config: '.trivy.yaml'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4
        with:
          sarif_file: 'trivy-results.sarif'
